export FOX_BUILD_DEVICE="beryl"
export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1
export ALLOW_MISSING_DEPENDENCIES=true
export LC_ALL="C"
export OF_FORCE_PREBUILT_KERNEL=1
export OF_DEFAULT_KEYMASTER_VERSION=4.1
